### ISSUE TITLE
flip.py feature request

### ISSUE THREAD

**Issue by edwardslabs** [CloudBotIRC/CloudBot#100]
It would be great to have flipped characters for caps and numbers if possible. 

Also currently the j doesn't flip correctly.

    .flip j
    ( ﾉ⊙︵⊙）ﾉ ︵ ظ

**Comment by Zarthus** [comment]
can just `.lower()` uppercase characters, the plugin doesn't look very coder-friendly when it comes to finding extra characters to flip. 
https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/flip.py#L8-L48

**Comment by lukeroge** [comment]
I've fixed J, and forced lowercase. I don't think theres any good way to flip numbers, sorry :(
