### ISSUE TITLE
factoids.py case sensitivity

### ISSUE THREAD

**Issue by edwardslabs** [CloudBotIRC/CloudBot#103]
In the regex hook for factoids.py the keyword is forced to lower case as seen below.
https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/factoids.py#L140

However in the remember command adding a keyword with caps is allowed and it is not forced to .lower().

This makes it possible to add a fact that can never be retrieved. If the goal is to keep the keywords case insensitive then https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/factoids.py#L77-81 should add word = word.lower().

If case sensitive factoids should be allowed than .lower should be removed from https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/factoids.py#L140

**Comment by lukeroge** [comment]
Thanks for noticing this! The initial idea was for factoids to be case-insensitive, because I can't really see a use case for case-sensitive factoids. I'll fix this for the next release.
