### ISSUE TITLE
Issue with the 'dictionary command. The command spits up the error "Error reaching ninjawords.com: 502"

### ISSUE THREAD

**Issue by KamranMackey** [CloudBotIRC/CloudBot#116]
The service that the 'dictionary command uses has been down for the past few days, and I was wondering if the service could be changed to something else, such as http://www.dictionary.com or something similar, as I unfortunately don't see Ninjawords coming back up anytime soon.

Wordnik seems like a good candidate instead: http://developer.wordnik.com/

**Comment by edwardslabs** [comment]
http://developer.wordnik.com/ looks promising. According to their terms say that free api keys are limited to 15,000 queries per hour. They do word of the day, random words, definitiions and entymology. I have requested an API key. If things work as advertised this api could replace word of the day, entymology. 

The other option is http://www.dictionaryapi.com/ but that only returns XML and I would much rather deal with JSON.

**Comment by KamranMackey** [comment]
Gonzo fixed the issue in PR #123, so I'm closing the issue now.
