### ISSUE TITLE
osrc plugin is down.

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#126]
https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/osrc.py

"The Open Source Report Card is temporarily (hopefully) out of service due to breaking changes with the GitHub API. Thanks for your understanding! <3" right from http://osrc.dfm.io/

**Comment by lukeroge** [comment]
I'll remove it for now. It's been broken for a long time.
