### ISSUE TITLE
Completely rewrite cleverbot.py - it's awful

### ISSUE THREAD

**Issue by lukeroge** [CloudBotIRC/CloudBot#137]
srsly. wat

**Comment by lukeroge** [comment]
it uses custom url paramater encoding

**Comment by lukeroge** [comment]
it has custom html quote implementation

**Comment by lukeroge** [comment]
and wtf is with this key_list + arg_list pseudo-dictionary. who wrote this?

**Comment by lukeroge** [comment]
ohgod

**Comment by urbels** [comment]
u mad? :D

**Comment by lukeroge** [comment]
Thanks @foxlet
