### ISSUE TITLE
Feature request CTCP hook

### ISSUE THREAD

**Issue by disconsented** [CloudBotIRC/CloudBot#155]
I would like my bot to be able to do things once it has received a response to a CTCP request

**Comment by daboross** [comment]
There isn't a specific CTCP hook as of now, but it is very possible to just use a regex to find CTCP messages and reply to them. See https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/core_ctcp.py.

```python
@hook.regex(r'^\x01CTCP_NAME .*\x01$')
fn my_ctcp_hook(match):
    ctcp_contents = match.group(1)
    # ...
```

**Comment by daboross** [comment]
As of the current version, CTCP hooks should be created with the following syntax:

```python
@asyncio.coroutine
@hook.event(EventType.other)
def ctcp_version(irc_ctcp_text):
    if irc_ctcp_text is not None and irc_ctcp_text.split(None, 1)[0] == "CTCP_NAME":
        # ...

**Comment by daboross** [comment]
In any case, I think this issue can be closed as resolved.
