### ISSUE TITLE
Plpaste is timing out.

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#169]
https://www.irccloud.com/pastebin/fjG3csXh/

**Comment by MikeRixWolfe** [comment]
http://hasteb.in is down. Can update cloudbot/util/web.py to point to http://hastebin.com or wait for hasteb.in to come back up.

**Comment by edwardslabs** [comment]
Hastebin pastes seem to be working again can you confirm?
