### ISSUE TITLE
When bouncer/ircnetwork goes down while bot is up, it breaks.

### ISSUE THREAD

**Issue by Arzte** [CloudBotIRC/CloudBot#171]
Steps to reproduce (since I can't provide a log)
Step one: Stop the network/bouncer the bot is on for 5-10 mins.
Step two: Profit

**Comment by TheDoctorsLife** [comment]
Update, http://pastebin.com/w6fwGJgp

**Comment by astrutt** [comment]
Still able to reproduce, the bot has never successfully reconnected to an irc network when it is disconnected for any reason. It simply hangs with no error and never tries to reconnect. Please fix.
