### ISSUE TITLE
Diagnosing "Killed"

### ISSUE THREAD

**Issue by disconsented** [CloudBotIRC/CloudBot#175]
Trying to start my bot after switching from a hackey python version to the offical debian 8 version (3.4.2)

How do I go about diagnosing this issue?
https://gist.github.com/disconsented/725b31a56a773d8896d4

**Comment by edwardslabs** [comment]
It looks like you haven't installed any of the required modules:  https://github.com/CloudBotIRC/CloudBot/wiki/Installing-on-*nix

There may be something else going on but start buy getting all the requirements installed.

**Comment by disconsented** [comment]
Yeah I was missing lxml somhow (my hackey version already had it) since I was running on a 512MB of RAM VPS I needed to setup swap in order to install it (https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps)
