### ISSUE TITLE
The config isn't updated/rewritten to disk when the config dict is changed

### ISSUE THREAD

**Issue by pangeacake** [CloudBotIRC/CloudBot#176]
some kind of update system should be implemented

**Comment by lukeroge** [comment]
config dict should not be changed

**Comment by PangeaCake** [comment]
Doesn't .adduser and related commands change the dict? or something else at least

I'm pretty sure those commands don't actually save the info do they? Where do they save it?

**Comment by Red-M** [comment]
https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/admin_bot.py#L198

**Comment by Red-M** [comment]
Does this answer your question?
