### ISSUE TITLE
system module's psutil functions are not working

### ISSUE THREAD

**Issue by tuxxy** [CloudBotIRC/CloudBot#226]
The psutil functions do not work, this is because system.py is using deprecated function names from the psutil library.

Here are the tracebacks:

Traceback (most recent call last):

    cpu_usage = process.get_cpu_percent()
        AttributeError: 'Process' object has no attribute 'get_cpu_percent'

and

    cpu_usage = process.get_cpu_percent()
        AttributeError: 'Process' object has no attribute 'get_cpu_percent'

These function names were deprecated in version 2.0.0 of psutil.

I'll be making a pull request shortly.

**Comment by astrutt** [comment]
Thanks TUX!!!

**Comment by tuxxy** [comment]
Thanks for the merge.
