### ISSUE TITLE
Doesn't recognize as admin despite being in the json

### ISSUE THREAD

**Issue by ihatevim** [CloudBotIRC/CloudBot#230]
http://i.imgur.com/t02JtCu.png
http://i.imgur.com/wBooUlo.png
Like the title says, the bot won't recognize me as admin no matter what I try. 
http://i.imgur.com/7fzp0sW.png

**Comment by edwardslabs** [comment]
try `ihatevim!*@*` or `*!*@the.aether.consumes.you`

**Comment by daboross** [comment]
Are you sure your ident is `ihatevim!ihatevim@the.aether.consumes.you` and not `ihatevim!~ihatevim@the.aether.consumes. you`? I think you can check this with whois

**Comment by ihatevim** [comment]
`ihatevim!*@*` worked thank you so much
