### ISSUE TITLE
Join event does not have the channel information

### ISSUE THREAD

**Issue by sbeparey** [CloudBotIRC/CloudBot#231]
When a user joins a channel, the raised event does not have any information about the said channel. Even the log shows "None." 

Update: This only happens on certain IRC network like Snoonet.

**Comment by daboross** [comment]
Is this fixed, or did you find a fix for it? If you found some other way to fix it it would be awesome if you could help future users.

If not, I might be able to find something out about this, although I haven't run into it myself.

**Comment by sbeparey** [comment]
@daboross This isn't fixed in the official repo but I "fixed" it on my end. I got tired of waiting around on them, so I just closed it. I'm not proud of the solution because it's kind of hacky. For me it works on Snoonet, it should work on other networks as well but it hasn't been tested elsewhere.

On event.py find the line: self.chan = channel (should be around 124) and replace it with the following code:
`            if channel is not None:
                self.chan = channel
            else:
                try:
                    raw = irc_raw.split(':')
                    if raw[-1].startswith('#'):
                        self.chan = raw[-1].lower()
                    elif raw[1] and raw[1].startswith('#'):
                        self.chan = raw[1].lower()
                    elif raw[2] and raw[2].startswith('#'):
                        self.chan = raw[2].lower()
                except:
                    pass`

**Comment by daboross** [comment]
Thank you, that is helpful! Sorry the team hasn't paid much attention to this issue.

If you want to do a less hacky fix, it might be best to include the code above in https://github.com/CloudBotIRC/CloudBot/blob/master/cloudbot/clients/irc.py#L397.

If you could print and share a few lines of what irc_raw looks like for your bot, I could probably get a more permanent-y fix for it in the main repository.

**Comment by sbeparey** [comment]
okay, that worked out really well, thanks!
