### ISSUE TITLE
.help command returns disabled commands

### ISSUE THREAD

**Issue by tsujin** [CloudBotIRC/CloudBot#235]
Hello everyone. I downloaded CloudBot and disabled all plugins except the ones I had written which are specific to the IRC channel I use it in (and the .help command itself). However, when the .help command is used it still returns ALL plugins. It seems to me that it would make more sense if .help only returned plugins that the user can actually use.

**Comment by daboross** [comment]
Fixed in https://github.com/CloudBotIRC/CloudBot/commit/28d0cc7bc8720cd01fb12ab67f1d65d1a0ebe2a0.
