### ISSUE TITLE
Bot poorly handles befriending ducks using pizza 

### ISSUE THREAD

**Issue by olligobber** [CloudBotIRC/CloudBot#236]
`<olligobber> .bef with pizza`

`<gonzobot> (olligobber) The duck said no, maybe bribe it with some pizza? Ducks love pizza don't they? You can try again in 7 seconds.`

`<olligobber> .bef with more pizza`

`<gonzobot> olligobber you befriended a duck in 20.578 seconds! You have made friends with ^^^ ducks in #^^^.`

**Comment by pangeacake** [comment]
I believe this isn't a default plugin..

**Comment by daboross** [comment]
As pangeacake said, this is not a plugin which is built into CloudBot, and thus does not receive help here.

Please resubmit this to the repository/person who made the "befriend" plugin.
