### ISSUE TITLE
Installing Error: Enchant c library not found

### ISSUE THREAD

**Issue by misaka00251** [CloudBotIRC/CloudBot#251]
Well I use this command to install something but it didn't work:
pip install -r requirements.txt
It says "Enchant c library not found."
My OS is CentOS 6 and I can't find any answers of that.

**Comment by misaka00251** [comment]
Well I found the solution of that
use this:
# sudo pip install -r requirements.txt

But now because my CentOS pre-installed python 2.6, so when I run this it always jumps to 2.6:

# sudo python
Python 2.6 ....

I make installed python3 and can run "python3" in my terminal, but I can't run "sudo python 3".

**Comment by knight-ryu12** [comment]
whoa. so big.


iPad$B$+$iAw?.(B

2016/10/19 19:51$B!"(BWind Reiki <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by knight-ryu12** [comment]
I'd recommend adding seveal repo... I think

**Comment by misaka00251** [comment]
Error here:
Command "/usr/bin/python -u -c "import setuptools, tokenize;
__file__='/tmp/pip-build-MaKm3m/lxml/setup.py';exec(compile(
getattr(tokenize, 'open', open)(__file__).read().replace('\r
\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Cj
iN_F-record/install-record.txt --single-version-externally-m
anaged --compile" failed with error code 1 in /tmp/pip-build
-MaKm3m/lxml/
