### ISSUE TITLE
Hook.commands can only be lowercase

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#49]
When testing out a new command Luke and i found out that commands have to be lowercase for cloudbot to output even tho its says its loaded.

```py
@hook.command("ForgeGradle", "FG")
def FG(message):
	message("What is ForgeGradle?");
	message("ForgeGradle is made by AbrarSyed. It allows forge to work with gradle and make modding Minecraft easier.")
	message("If you would like to help make it easier please feel free to help https://github.com/MinecraftForge/ForgeGradle.")
	return
```
This will not work if you type `.fg` or even  `.FG` 

https://www.irccloud.com/pastebin/AiCt9pOF
^lowercase

**Comment by daboross** [comment]
@lukeroge Command matching is already case-insensitive, we just don't sanitize command hooks xD.

I don't really see the benefit of having upper case command declarations, but it's an easy fix.

**Comment by lukeroge** [comment]
"we just don't sanitize command hooks"
Not sure what you mean exactly by this

**Comment by daboross** [comment]
Just that we assume they are lower case, not making sure that they are.

**Comment by lukeroge** [comment]
Well, I added code in the hook system to `.lower()` all aliases with #ba0552a, so this should no longer be an issue. Closed!
