### ISSUE TITLE
Multiple functions allowed with the same name 

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#50]
```py
from cloudbot import hook
 
@hook.command("smr", "stopmodreposts")
def smr(message, chan):
    if chan == "#stopmodreposts":
            return None
    message("What is StopModReposts?")
    message("A movement against mods being re-hosted (and monetized) without the author's permission.")
    message("The website is http://stopmodreposts.org/")
    message("Join #StopModReposts to discuss and get involved")
    return
    
    
@hook.command("smrsite", "stopmodrepostsite")
def smr(message, chan):
    if chan == "#stopmodreposts":
            message("The website is http://stopmodreposts.org/")
    return None
```

^loaded but after 5 mins stopped working

**Comment by daboross** [comment]
Were there any errors when it stopped working? I doubt it's related to the fact that you defined two commands in the same name.

Python should just overwrite one with the other, our plugin loading system doesn't do anything with function names (besides use them as command names if you don't provide any arguments to hook.command())

**Comment by daboross** [comment]
I don't think there is much we can do for this. Python itself will overwrite function definitions when two functions have the same name. I don't think there is any easy way for us to detect this.

**Comment by lukeroge** [comment]
I think this might have to be a WontFix
