### ISSUE TITLE
Using "Ignore" in Configuration does not stop regex.

### ISSUE THREAD

**Issue by foxlet** [CloudBotIRC/CloudBot#58]
When ignoring an user (or bot) via their hostmask in config.json, regex still runs on messages by the ignored users. Reddit.py, for example, will still pick up links by ignored users.

**Comment by lukeroge** [comment]
Can not reproduce. Rewrote ignore anyway because I'm crazy

**Comment by foxlet** [comment]
Old bug has been fixed in RoboCop's version jump.
