### ISSUE TITLE
[Suggestion] threadsafe bot memory dict

### ISSUE THREAD

**Issue by PangeaCake** [CloudBotIRC/CloudBot#63]
A threadsafe dict implementation that plugins can use as memory (like Willie has) would be very useful.

**Comment by lukeroge** [comment]
Sorry, not entirely sure what you mean, you can pretty much just store data in globals

**Comment by daboross** [comment]
Since plugins don't actually run on different threads unless you specifically ask them to, there isn't really a reason to not just use a `dict()` in your plugin.
