### ISSUE TITLE
Proposal: Create a proper stable (versioned) release for CloudBot

### ISSUE THREAD

**Issue by lukeroge** [CloudBotIRC/CloudBot#71]
I've had some complaints that it's very hard to keep up-to-date with Cloudbot and use new versions because of the constant changes, massive amount of vague commits, and the fact that there is often broken code on the main branch.

And I agree completely.

So I'd like to get some ideas and fix that. My initial proposal is to create a new branch, **master**, and set it as the main branch on the repository. We will do periodic releases from the current **python3.4** branch when code is stable and tested. We will assign these releases version numbers. We will provide a changelog of all changes whenever a release is pushed to the stable **master** branch.

**Comment by Zarthus** [comment]
https://github.com/CloudBotIRC/CloudBot/releases & git tags should suffice for stable releases, a new branch is not necessary.

**Comment by lukeroge** [comment]
The idea of a branch is that a user can just clone that branch and git will always update to the latest stable release.

**Comment by lukeroge** [comment]
Done :)
