### ISSUE TITLE
@hook.every(60) seconds

### ISSUE THREAD

**Issue by PangeaCake** [CloudBotIRC/CloudBot#82]
@lukeroge mentioned this in IRC, just making an issue for it.

**Comment by PangeaCake** [comment]
A @hook.limit(60) seconds would be nice to, to rate limit a command per user, though the implementation for that could be difficult (and I'm not sure how useful it might be)

**Comment by PangeaCake** [comment]
A @hook.limit(60) seconds would be nice to, to rate limit a command per user, though the implementation for that could be difficult (and I'm not sure how useful it might be)

**Comment by PangeaCake** [comment]
A @hook.limit(60) seconds would be nice to, to rate limit a command per user, though the implementation for that could be difficult (and I'm not sure how useful it might be)

**Comment by lukeroge** [comment]
@hook.periodic is done!
