### ISSUE TITLE
asyncio Debug on linux

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#96]
https://www.irccloud.com/pastebin/KzWEqYgR

@lukeroge already knows just putting it here so no1 forgets.

**Comment by lukeroge** [comment]
```DEBUG:asyncio:poll 0.000 took 0.000 seconds```

**Comment by lukeroge** [comment]
```DEBUG:asyncio:poll 0.000 took 0.000 seconds```

**Comment by lukeroge** [comment]
```DEBUG:asyncio:poll 0.000 took 0.000 seconds```

**Comment by lukeroge** [comment]
I tried a fix, tell me if this issue is still happening on the latest release
